// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tower_Section_Catalogue.Data;

#nullable disable

namespace Tower_Section_Catalogue.Migrations
{
    [DbContext(typeof(Tower_Section_CatalogueContext))]
    partial class Tower_Section_CatalogueContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Tower_Section_Catalogue.Models.Shell", b =>
                {
                    b.Property<int>("ShellPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShellPosition"), 1L, 1);

                    b.Property<double>("BottomDiameter")
                        .HasColumnType("float");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<double>("SteelDensity")
                        .HasColumnType("float");

                    b.Property<double>("Thickness")
                        .HasColumnType("float");

                    b.Property<double>("TopDiameter")
                        .HasColumnType("float");

                    b.Property<int>("TowerSectionId")
                        .HasColumnType("int");

                    b.HasKey("ShellPosition");

                    b.HasIndex("TowerSectionId");

                    b.ToTable("Shell");
                });

            modelBuilder.Entity("Tower_Section_Catalogue.Models.TowerSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double>("bottomDiameter")
                        .HasColumnType("float");

                    b.Property<double>("lenght")
                        .HasColumnType("float");

                    b.Property<string>("partNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("topDiameter")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TowerSection");
                });

            modelBuilder.Entity("Tower_Section_Catalogue.Models.Shell", b =>
                {
                    b.HasOne("Tower_Section_Catalogue.Models.TowerSection", "TowerSection")
                        .WithMany("Shells")
                        .HasForeignKey("TowerSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TowerSection");
                });

            modelBuilder.Entity("Tower_Section_Catalogue.Models.TowerSection", b =>
                {
                    b.Navigation("Shells");
                });
#pragma warning restore 612, 618
        }
    }
}
